name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: "latest"

      - name: Build
        run: ghc -o temperament4fft temperament4fft.hs

      - name: Run
        run: ./temperament4fft
